version: 2
jobs:
  build:
    docker:
      - image: ryanjbaxter/pipeline-base
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
      TERM: dumb
    branches:
      ignore:
        - gh-pages # list of branches to ignore
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: sc-config-{{ .Branch }}
      - run:
          name: "Download dependencies"
          command: ./mvnw -s .settings.xml -U --fail-never dependency:go-offline || true
      - save_cache:
          key: sc-oconfig-{{ .Branch }}
          paths:
            - ~/.m2
      - run:
          name: "Creating user"
          command: |
            groupadd -g 888 configuser && \
            useradd -r -u 888 -m -g configuser configuser && \
            passwd -d configuser && \
            su configuser
      - run:
          name: "Running build"
          command: ./mvnw -s .settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent install -U -P sonar -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      - run:
          name: "Aggregate test results"
          when: always
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/junit/
            find . -type f -regex ".*/target/.*-reports/.*" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
            bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /junit/
          destination: artifacts
      - store_test_results:
          path: /junit/
          destination: testartifacts